### ISSUE TITLE
When the code of FeTaQA is avaliable?

### ISSUE THREAD

**Issue by wentinghome** [Yale-LILY/FeTaQA#1]
Hi,

Thanks so much for this great work!
I'm wondering when the code of FeTaQA will be available since I'm trying to run the code and see some generated cases (especially the end-to-end model).

**Comment by jeffersonHsieh** [comment]
Hi, thanks for your interest and sorry for the delay. We've released the T5 end2end model. Stay tuned for the tapas based model release!
